function p = prewitt(block)
block = double(block);
Gx = [-1  0  1;
      -1  0  1;
      -1  0  1];
Gy = [-1 -1 -1;
       0  0  0;
       1  1  1];
Gv = imfilter(block, Gx, 'replicate');
Gh = imfilter(block, Gy, 'replicate');
meanGv = mean2(abs(Gv));
meanGh = mean2(abs(Gh));
[magVH, dirVH] = imgradient(Gv, Gh);
magVH = mean2(magVH);
dirVH = mean2(dirVH);
Gx = [ 0  1  1;
      -1  0  1;
      -1 -1  0];
Gy = [-1 -1  0;
      -1  0  1;
       0  1  1];
Gur = imfilter(block, Gx, 'replicate');
Gul = imfilter(block, Gy, 'replicate');
meanGUR = mean2(abs(Gur));
meanGUL = mean2(abs(Gul));
[magD, dirD] = imgradient(Gur, Gul);
magD = mean2(magD);
dirD = mean2(dirD);
p = [meanGv meanGh magVH dirVH meanGUR meanGUL magD dirD];
end